# Generated by Django 2.1 on 2019-06-28 16:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('A', 'Active'), ('D', 'Deactive'), ('T', 'Trash')], default='A', max_length=1)),
                ('name', models.CharField(help_text='Author name', max_length=255, verbose_name='Author name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('A', 'Active'), ('D', 'Deactive'), ('T', 'Trash')], default='A', max_length=1)),
                ('name', models.CharField(help_text='Book name', max_length=255, verbose_name='Book name')),
                ('isbn', models.CharField(help_text='isbn', max_length=20, verbose_name='isbn')),
                ('number_of_pages', models.IntegerField(help_text='Number of Pages', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of Pages')),
                ('publisher', models.CharField(help_text='Publisher', max_length=255, verbose_name='Publisher')),
                ('release_date', models.DateField(help_text='Release Date', verbose_name='Release Date')),
                ('authors', models.ManyToManyField(help_text='authors', to='app.Author', verbose_name='authors')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('A', 'Active'), ('D', 'Deactive'), ('T', 'Trash')], default='A', max_length=1)),
                ('name', models.CharField(help_text='Country', max_length=255, verbose_name='Country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='books',
            name='country',
            field=models.ForeignKey(help_text='Country', on_delete=django.db.models.deletion.CASCADE, to='app.Country', verbose_name='Country'),
        ),
    ]
