# Generated by Django 2.1 on 2019-06-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.CharField(help_text='isbn', max_length=20, unique=True, verbose_name='isbn'),
        ),
    ]
